### PR TITLE
Validation for fromBytes

### LINKED ISSUE #22: [Crash/Fuzzing] TypeError in ssz library during BeaconBlock deserialize
**Describe the bug**

During fuzzing with [beaconfuzz](https://github.com/sigp/beacon-fuzz), I found this TypeError crash inside ssz library when trying to deserialize a beaconblock.

**Expected behavior**

Should throw a custom Error.

**Steps to Reproduce**

crash_TypeError_block_lodestar.js:
``` js
var mainnet_1 = require("@chainsafe/lodestar-types/lib/ssz/presets/mainnet");

buf = Buffer.from('0100000000000000ae000000000000000a0a0a0a2a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a000000000000000000000000000000000000000000000000000000000000000054000000b69753a1c80a81b630fedc668c19ac093cbcc44fe1e294ff7164de52ef0f109a602b7065cb7b21f14a65cbcbbd4455960cef385d552e393e2d47b340cab50291ce81256c1b8239d6ebc1ab84ae2410f6b9fb3dc989e15a9fe9a4431393e1da5d0000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dc000000dc000000dc000000dc000000dc00ddff', 'hex')

mainnet_1.types.BeaconBlock.deserialize(buf);
```

Run:
``` sh
$ npm i @chainsafe/lodestar-types

$ node crash_TypeError_block_lodestar.js
XXX/lodestar/node_modules/@chainsafe/ssz/lib/types/basic/uint.js:176
      output += BigInt(data[offset + i]) << BigInt(8 * i);
                ^

TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at BigIntUintType.fromBytes (XXX/lodestar/node_modules/@chainsafe/ssz/lib/types/basic/uint.js:176:17)
    at XXX/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:133:40
    at Array.forEach (<anonymous>)
    at ContainerStructuralHandler.fromBytes (XXX/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:112:39)
    at XXX/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:135:51
    at Array.forEach (<anonymous>)
    at ContainerStructuralHandler.fromBytes (XXX/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:112:39)
    at XXX/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/array.js:209:54
    at Function.from (<anonymous>)
```

**Desktop (please complete the following information):**

* OS: `Ubuntu 18.04`
* [@chainsafe/lodestar-types](https://www.npmjs.com/package/@chainsafe/lodestar-types): `0.8.0`
* node -v: `v12.9.1`

### PR DESCRIPTION
**Pull request by tuyennhv**
resolves #22 #23

### CODE REVIEW

File: src/backings/structural/abstract.ts [hunk 1]
```diff
@@ -34,13 +34,31 @@ export class StructuralHandler<T extends object> {
...
     throw new Error("Not implemented");
   }
+  validateBytes(data: Uint8Array, start: number, end: number): void {
+    if (!data) {
+      throw new Error("Data is null or undefined");
+    }
+    if (data.length === 0) {
+      throw new Error("Data is empty");
+    }
+    if (start < 0 || start >= data.length) {
```
Comment (dapplion) [inline src/backings/structural/abstract.ts:44]: Maybe we can add an error for each case with the specific message: "start is negative", "start is greater than length"

File: src/backings/structural/array.ts [hunk 2]
```diff
@@ -48,6 +48,7 @@ export class BasicArrayStructuralHandler<T extends ArrayLike<unknown>> extends S
     return newValue;
   }
   fromBytes(data: Uint8Array, start: number, end: number): T {
+    super.validateBytes(data, start, end);
```
Comment (wemeetagain) [inline src/backings/structural/array.ts:51]: I think all these instances of `super.validateBytes` should be converted to `this.validateBytes`. We'd likely only need to use `super.validateBytes` if we have override `validateBytes` and need to call the super's method, too.

Comment (tuyennhv) [reply src/backings/structural/array.ts]: yeah it's done
